apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: product-app
  labels:
    app: api-gateway
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        version: v1
        monitoring: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: api-gateway
      containers:
        - name: api-gateway
          image: docker.io/princewillopah/product-app-api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.observability-stack:4317"
            - name: OTEL_SERVICE_NAME
              value: "api-gateway"
            - name: ORDER_SERVICE_URL
              value: "http://order-service.product-app:8080"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service.product-app:8080"
            - name: ANALYTICS_SERVICE_URL
              value: "http://analytics-service.product-app:8080"
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              cpu: 150m
              memory: 192Mi
            limits:
              cpu: 500m
              memory: 512Mi
