apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: product-app
  labels:
    app: api-gateway
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
