apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: order-service
  namespace: product-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: order-service
subjects:
  - kind: ServiceAccount
    name: order-service
    namespace: product-app
