apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: product-app
  labels:
    app: product-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  selector:
    app: product-service
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
