{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled | default true }}
{{- with $svc.hpa }}
{{- if .enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "product-app.labels" (dict "ctx" $ "name" $name) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}
  minReplicas: {{ .minReplicas | default 2 }}
  maxReplicas: {{ .maxReplicas | default 5 }}
  metrics:
    {{- toYaml .metrics | nindent 4 }}
  {{- with .behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
