{{- if .Values.rbac.create }}
{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled | default true }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "product-app.labels" (dict "ctx" $ "name" $name) | nindent 4 }}
rules:
  {{- toYaml ($svc.rbacRules | default $.Values.rbac.rules) | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "product-app.labels" (dict "ctx" $ "name" $name) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $name }}
subjects:
  - kind: ServiceAccount
    name: {{ $name }}
    namespace: {{ $.Values.global.namespace }}
{{- end }}
{{- end }}
{{- end }}
